# Generated by Django 2.0.6 on 2018-06-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('company', '培训机构'), ('person', '个人'), ('university', '高校')], default='universiy', max_length=20, verbose_name='机构类别'),
        ),
    ]
