# Generated by Django 2.0.6 on 2018-06-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorg_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='organization/%Y/%m', verbose_name='机构图片'),
        ),
    ]
