# Generated by Django 2.0.6 on 2018-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180621_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='课程类别'),
        ),
    ]
