# Generated by Django 2.0.6 on 2018-06-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='课程标签'),
        ),
    ]
