# Generated by Django 2.0.6 on 2018-06-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_know',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='课程公告'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='教师讲解'),
        ),
    ]
