# Generated by Django 2.0.6 on 2018-06-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20180622_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(upload_to='resource/%Y/%m', verbose_name='课程资源'),
        ),
    ]
