# Generated by Django 2.0.6 on 2018-06-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='index',
            field=models.IntegerField(default=100, verbose_name='轮播顺序'),
        ),
    ]
